/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#fdf8f8',
        'on-background': '#1c1b1c',
        surface: {
          DEFAULT: '#fdf8f8',
          dim: '#ddd9d9',
          bright: '#fdf8f8',
          variant: '#e6e1e1',
        },
        'on-surface': '#1c1b1c',
        'on-surface-variant': '#444748',
        'surface-container': {
          lowest: '#ffffff',
          low: '#f7f2f2',
          DEFAULT: '#f1eded',
          high: '#ece7e7',
          highest: '#e6e1e1',
        },
        primary: {
          DEFAULT: '#000000',
          fixed: '#e5e2e1',
          'fixed-dim': '#c8c6c5',
        },
        'on-primary': '#ffffff',
        'on-primary-fixed': '#1c1b1b',
        'on-primary-fixed-variant': '#474746',
        'primary-container': '#1c1b1b',
        'on-primary-container': '#858383',
        secondary: {
          DEFAULT: '#5e5e5e',
          fixed: '#e4e2e2',
          'fixed-dim': '#c8c6c6',
          container: '#e4e2e2',
        },
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#1b1c1c',
        'on-secondary-fixed-variant': '#474747',
        'on-secondary-container': '#646464',
        tertiary: {
          DEFAULT: '#000000',
          fixed: '#e3e2e2',
          'fixed-dim': '#c7c6c6',
          container: '#1b1c1c',
        },
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#1b1c1c',
        'on-tertiary-fixed-variant': '#464747',
        'on-tertiary-container': '#848484',
        outline: {
          DEFAULT: '#747878',
          variant: '#c4c7c7',
        },
        error: {
          DEFAULT: '#ba1a1a',
          container: '#ffdad6',
        },
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f4f0f0',
        'inverse-primary': '#c8c6c5',
        'surface-tint': '#5f5e5e',
      },
      fontFamily: {
        display: ['Playfair Display', 'serif'],
        body: ['Literata', 'serif'],
        label: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '32px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '28px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      spacing: {
        unit: '8px',
        gutter: '24px',
        'margin-mobile': '24px',
        'margin-desktop': '120px',
        'max-width-content': '720px',
        'safe-top': 'env(safe-area-inset-top)',
        'safe-bottom': 'env(safe-area-inset-bottom)',
        'safe-left': 'env(safe-area-inset-left)',
        'safe-right': 'env(safe-area-inset-right)',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
