/**
 * 图书馆语气库（UI 重构建议书 7.8）——面向用户的一切文案先入库存审。
 * 语气总则：拟人，不卖萌。少字、具象动词、说清后果；技术细节放括号。
 */
export const COPY = {
  toast: {
    /** 备份恢复 */
    backupVersionUnsupported: '这份备份来得太早——版本不受支持',
    backupRestored: '馆藏已从备份恢复',
    backupBroken: '这份备份打不开——文件可能损坏或格式不对',
    /** 手记 */
    noAnnotations: '这本书还没有手记。读的时候，长按一句话就能把它贴上墙',
    /** 馆务 */
    storageComingSoon: '馆容量的整理还在筹备中',
  },
  dialog: {
    /** 恢复备份确认（破坏性：覆盖） */
    backupRestoreTitle: '用备份覆盖现在的馆藏？',
    backupRestoreMessage: '当前的阅读进度、书签与手记会被备份里的内容替换，且无法撤销。',
    backupRestoreConfirm: '覆盖导入',
    backupRestoreCancel: '先不',
  },
  /** 手记（划线/批注分离：划线零输入，批注弹笔记） */
  annotation: {
    highlightAction: '划线',
    annotateAction: '批注',
    copyAction: '复制',
    copiedToast: '已复制到剪贴板',
    copyFailedToast: '复制失败，请重试',
    notePlaceholder: '写点什么…（留空则仅划线）',
    saveNote: '保存批注',
    saveHighlightOnly: '仅划线',
    pureHighlight: '纯划线',
    clearToPureHighlight: '清空文字即转为纯划线',
    pageNote: '页注',
    pageNotePlaceholder: '给这一页写点什么…',
    addPageNote: '页级手记',
    readerNotes: '手记',
    pageNoteSaved: '已贴上这页手记',
    deleted: '已删除手记',
    readerSettings: '阅读设置',
    goTo: '回到此处',
    remove: '删除',
    edit: '编辑',
    save: '保存',
    cancel: '取消',
    close: '关闭',
    styleLabels: {
      highlight: '水彩笔',
      underline: '下划线',
      wavy: '波浪线',
    },
  },
  /** 书内检索 */
  searchInBook: {
    title: '检索本书',
    placeholder: '在这本书里找一个词',
    hint: '至少两个字符；命中按章节排列',
    noResults: '这本书里没有找到',
    hitCount: (n: number) => `找到 ${n} 处`,
    extracting: '正在提取文本层…',
    extractFailed: '这本书的文本提不出来——可能没有文字层',
    search: '检索本书',
  },
  /** 摘抄墙 */
  notesWall: {
    searchPlaceholder: '找一句划过的句子',
    filterAll: '全部',
    filterHighlight: '纯划线',
    filterNote: '批注',
    filterBookAll: '所有书',
    filterTagAll: '所有标签',
    emptyFiltered: '没有符合条件的手记——换个词或放宽筛选',
    exportAll: '导出整墙 Markdown',
  },
  /** 回望席（门厅的呼出环节） */
  revisit: {
    sectionTitle: '回望席',
    anniversaryBook: (years: number) => `这本书入馆 ${years} 周年了`,
    anniversaryNote: (years: number) => `${years} 年前的今天，你划下了这句`,
    revisitAnnotated: '这本书留了你的手记，很久没翻了',
    revisitLongUnread: '它在书架上等你很久了',
    revisitRandom: '今天想从这本开始吗？',
    dismissToday: '今日不再看',
    goBack: '回望',
  },
  /** 漫画跨章续读：章末不落加载黑场，滚动自然接续下一章 */
  comicChapter: {
    chapterEnd: '本章完',
    nextChapter: (title: string) => `下一章 · ${title}`,
    preparingNext: '正在准备下一章…',
    bookEnd: '已经到最后一页',
    chapterStart: '已是本章第一页',
  },
  /** 全库检索（Search 页）：馆藏/手记/知识件三路聚合 */
  globalSearch: {
    placeholder: '搜书、手记或知识件…',
    booksSection: '馆藏',
    annotationsSection: '手记',
    knowledgeSection: '知识件',
    emptyTitle: '整座馆都没找到',
    emptyHint: '换个词试试——书名、划过的句子、术语都行',
    orphanBook: '已移出的书',
  },
  /** 知识件手工修订（修订模式）：AI 写错的直接改，看过的盖「校」章 */
  knowledgeEdit: {
    revise: '修订',
    reviseHint: 'AI 写错的地方直接改：点「改」修字，「删」去条目，核对过的盖校章',
    verifiedBadge: '已校验',
    verify: '盖校章',
    unverify: '撤校章',
    editEntry: '改',
    removeEntry: '删',
    saveRevision: '保存修订',
    revisedToast: '已修订',
    removedToast: '已删掉这条',
    relationName: '关系',
    relationNote: '说明',
    regenerateOverwriteTitle: '重新生成会盖掉你的修订',
    regenerateOverwriteMessage: (n: number) =>
      `这份知识件里有你改过的 ${n} 处内容，重新生成会全部替换，删掉的也会回来。`,
    regenerateConfirm: '盖掉重生成',
    regenerateCancel: '先留下',
  },
  /** 复习席：把读过变长在身上（术语卡/批注/生词派生的间隔重复队列） */
  review: {
    sectionTitle: '复习席',
    homeEntry: (n: number) => `今日待复习 ${n} 张`,
    homeEntryHint: '术语、批注与生词排成的卡，见一面记一面',
    sourceGlossary: '术语卡',
    sourceAnnotation: '手记',
    sourceVocab: '生词',
    showAnswer: '看答案',
    again: '忘了',
    good: '记得',
    easy: '熟了',
    againHint: '十分钟后这张会再回来',
    skip: '稍后',
    dismiss: '不再复习这张',
    dismissedToast: '这张卡收起来了',
    emptyNoCardsTitle: '馆里还没有可复习的卡',
    emptyNoCardsHint: '写下批注、给学术书生成术语卡、或查一个生词，它们会自动排进复习席',
    emptyTodayTitle: '今天没有到期的卡',
    doneTitle: '今天的复习收工了',
    doneHint: (n: number) => `今天见了 ${n} 张卡。忘了的稍后会回来，别的改天见。`,
    exportAnki: '导出 Anki 卡组',
    exportedToast: '已导出 Anki 卡组（TSV）',
  },
  /** 划词查词与生词本（外语学习闭环） */
  vocab: {
    lookupAction: '查词',
    lookupTitle: '查词',
    loading: '正在翻词典…',
    lookupFailed: '没查到——AI 服务没配好或网络不通',
    aiNotConfigured: '查词要用你自己的 AI 服务——先到设置里配好再来',
    saveToVocab: '收进生词本',
    savedToast: '已收进生词本，复习席里见',
    deletedToast: '已从生词本删掉',
    pageName: '生词本',
    pageIntro: (n: number) => `读外文书时查过的 ${n} 个词——都在复习席里排队`,
    emptyTitle: '生词本还空着',
    emptyHint: '阅读时选中一个词，点「查词」，释义就会收进来',
    goRead: '去书库挑一本',
    goReview: '去复习',
    notesEntry: '生词本',
    exportAll: '导出生词本',
    exportedToast: '已导出生词本 Markdown',
    contextLabel: '语境',
  },
  /** 问藏书（RAG 问答）：答案从你的书里来 */
  askLibrary: {
    pageName: '问藏书',
    pageHint: '答案从你的书里来——每一句都能翻回原文',
    placeholder: '问点什么，比如「哪本书讲过注意力机制」',
    askAction: '提问',
    scopeAllBooks: '全馆',
    phaseSearching: '正在翻书…',
    phaseAsking: '正在读选段…',
    searched: (n: number) => `翻了 ${n} 本书`,
    noHits: '馆藏里没有检索到相关内容',
    noHitsHint: '换个说法，或把范围缩到一本书再问',
    notConfigured: '问答要用你自己的 AI 服务——先到设置里配好',
    goSettings: '去设置',
    sourcesLabel: '出处',
    unlocated: '未定位到原文',
    backToSource: '回到原文',
    emptyTitle: '把整座馆当成一个脑子来问',
    emptyHint: '它会先翻你的书找到相关段落，再作答——答案带出处，出处能跳回原文',
    retry: '再问一次',
  },
  /** 引用格式导出（档案卡） */
  citation: {
    menuLabel: '引用格式',
    dialogTitle: '引用这本书',
    copyAction: '复制',
    copiedToast: '已复制',
    copyFailedToast: '复制失败，请重试',
    noAuthorHint: '档案里还没有作者——补上作者，引用更规范',
  },
  /** 手记输出侧：按主题导出 + 从划线生成提纲 */
  notesTheme: {
    exportByBook: '整墙导出（按书）',
    exportByTheme: '按主题导出（按标签）',
    untagged: '未分类',
    aiNotConfigured: '生成提纲要用你自己的 AI 服务——先到设置里配好',
    outlineAction: '生成提纲',
    outlineTitle: '提纲',
    outlineLoading: '正在整理你的划线…',
    outlineFailed: '提纲没生成——AI 服务没配好或网络不通',
    outlineEmpty: '划线还太少——攒够几条再来（可先按标签筛出一组）',
    outlineCopy: '复制提纲',
    outlineDownload: '下载 Markdown',
    outlineSources: (n: number) => `原料 · ${n} 条手记`,
  },
  /** 前情提要（欢迎回来卡）：久别续读的定向仪 */
  recap: {
    sheetTitle: '欢迎回来',
    awayDays: (n: number) => `离开这本书 ${n} 天了`,
    stoppedAt: (chapter: string, pct: number) => `上次停在${chapter} · 已读 ${pct}%`,
    stoppedAtPct: (pct: number) => `已读 ${pct}%`,
    tracesLabel: '你留下的痕迹',
    recapLabel: '前情提要',
    generateAction: '生成前情提要',
    generating: '正在翻你读过的部分…',
    failed: '前情没生成——AI 服务没配好或网络不通',
    aiNotConfigured: '生成前情要用你自己的 AI 服务——先到设置里配好',
    noPriorContent: '你从开头读起——没有更早的前情',
    unsupported: '漫画还没有文本层——先看看进度和你的手记吧',
    basedOn: (range: string) => `基于${range}`,
    nowLabel: '此刻',
    continueReading: '直接继续读',
    graphLink: '看看图谱',
    chip: (n: number) => `离开 ${n} 天 · 回想想`,
  },
  /** 跨书图谱：同名实体跨书归并（人物网/概念网/术语对照） */
  atlas: {
    pageName: '跨书图谱',
    pageHint: '同一人物/概念在不同书里的样子，并排看',
    tabCharacters: (n: number) => `人物网 · ${n} 书`,
    tabConcepts: (n: number) => `概念网 · ${n} 书`,
    tabGlossary: (n: number) => `术语对照 · ${n} 书`,
    emptyTitle: '跨书网络还连不起来',
    emptyHint: '至少要有两本书生成同类知识件（人物图谱/概念图谱/术语卡），这里才会把同名实体并到一起',
    sharedTerms: (n: number) => `${n} 个术语出现在多本书里`,
    singleBookTerms: (n: number) => `另有 ${n} 个术语只出现在一本书里`,
    disagreeHint: '两本书的说法不一样——分歧本身就是信息',
    inBooks: (n: number) => `出现于 ${n} 本书`,
    edgeInBooks: (n: number) => `${n} 本书都这么写`,
  },
  /** 划词翻译（句级选区）：查词管一个词，这里管一句话 */
  translate: {
    action: '翻译',
    loading: '正在翻译…',
    failed: '没译出来——AI 服务没配好或网络不通',
    aiNotConfigured: '翻译要用你自己的 AI 服务——先到设置里配好',
    sourceLabel: '原文',
    copyTranslation: '复制译文',
    copiedToast: '已复制',
    copyFailedToast: '复制失败，请重试',
    saveAsNote: '译文存为批注',
    savedToast: '已存为批注（原文 + 译文）',
  },
  /** 剪报台：粘贴文章按文本书入藏（第三类内容走现成管线） */
  clip: {
    sectionTitle: '剪报台',
    hint: '把网上读到的文章、帖子粘贴进来——按文本书入藏，划线、批注、知识库、复习一样不少',
    titleLabel: '标题',
    titlePlaceholder: '给这篇剪报起个名…',
    contentLabel: '正文（Markdown 或纯文本）',
    contentPlaceholder: '粘贴正文…',
    submit: '入藏',
    emptyToast: '标题和正文都要有',
    failedToast: '入藏失败，请重试',
  },
} as const;
