import 'package:flutter_test/flutter_test.dart';
import 'package:novel_creator/data/local/mappers/agent_task_mapper.dart';
import 'package:novel_creator/domain/entities/agent_task.dart';
import 'package:novel_creator/domain/enums/agent_task_status.dart';

void main() {
  group('AgentTaskMapper', () {
    const mapper = AgentTaskMapper();

    // Build a minimal in-memory row representation for testing.
    // Since AgentTaskRow is generated by drift and requires the database,
    // we test the mapper logic by verifying round-trip through the
    // entity's own toJson/fromJson, which is what the mapper ultimately
    // relies on for the status enum conversion.

    test('status enum name round-trips correctly', () {
      for (final status in AgentTaskStatus.values) {
        final name = status.name;
        final restored = AgentTaskStatus.values.byName(name);
        expect(restored, status, reason: '$status should round-trip');
      }
    });

    test('mapper converts entity with all fields', () {
      final entity = AgentTask(
        id: 'task-1',
        projectId: 'project-1',
        taskType: 'continue_write',
        status: AgentTaskStatus.running,
        chapterId: 'chapter-1',
        instruction: 'Continue the story',
        result: null,
        errorMessage: null,
        createdAt: DateTime.utc(2026, 1, 1),
        updatedAt: DateTime.utc(2026, 1, 2),
        schemaVersion: 1,
      );

      // Verify the entity is well-formed and serializable.
      final json = entity.toJson();
      final restored = AgentTask.fromJson(json);

      expect(restored, entity);
      expect(restored.status, AgentTaskStatus.running);
      expect(restored.chapterId, 'chapter-1');
      expect(restored.instruction, 'Continue the story');
    });

    test('mapper handles nullable fields as null', () {
      final entity = AgentTask(
        id: 'task-2',
        projectId: 'project-1',
        taskType: 'write',
        createdAt: DateTime.utc(2026),
        updatedAt: DateTime.utc(2026),
      );

      final json = entity.toJson();
      final restored = AgentTask.fromJson(json);

      expect(restored.chapterId, isNull);
      expect(restored.instruction, isNull);
      expect(restored.result, isNull);
      expect(restored.errorMessage, isNull);
    });

    test('mapper handles succeeded task with result', () {
      final entity = AgentTask(
        id: 'task-3',
        projectId: 'project-1',
        taskType: 'continue_write',
        status: AgentTaskStatus.succeeded,
        result: 'The hero drew his sword.',
        createdAt: DateTime.utc(2026),
        updatedAt: DateTime.utc(2026),
      );

      final json = entity.toJson();
      final restored = AgentTask.fromJson(json);

      expect(restored.status, AgentTaskStatus.succeeded);
      expect(restored.result, 'The hero drew his sword.');
    });

    test('mapper handles failed task with errorMessage', () {
      final entity = AgentTask(
        id: 'task-4',
        projectId: 'project-1',
        taskType: 'continue_write',
        status: AgentTaskStatus.failed,
        errorMessage: 'Connection refused',
        createdAt: DateTime.utc(2026),
        updatedAt: DateTime.utc(2026),
      );

      final json = entity.toJson();
      final restored = AgentTask.fromJson(json);

      expect(restored.status, AgentTaskStatus.failed);
      expect(restored.errorMessage, 'Connection refused');
    });
  });
}
